export { Home } from './Home'
export { Acerca } from './Acerca'
export { Productos } from './Productos'
export { Servicios } from './Servicios'
export { Error404 } from './Error404'
export { ProductosDetalle } from './ProductosDetalle'